repositories {
	maven {
		name 'Sonatype'
		url 'https://s01.oss.sonatype.org/content/repositories/releases/'
	}
}

ext {
	bomVersion = '4.14.4'
}

configurations {
	all {
		resolutionStrategy {
			force "com.exactpro.th2:bom:${bomVersion}",
					"org.apache.commons:commons-collections4:4.4",
					"io.grpc:grpc-stub:1.80.0",
					"io.grpc:grpc-api:1.80.0",
					"io.grpc:grpc-core:1.80.0",
					"io.grpc:grpc-netty:1.80.0",
					"io.grpc:grpc-protobuf:1.80.0",
					"io.grpc:grpc-services:1.80.0",
					'com.exactpro.th2:grpc-common:4.7.5',
					"io.vertx:vertx-core:4.5.24",
					"io.vertx:vertx-auth-common:4.5.24",
					"io.github.oshai:kotlin-logging:7.0.12",
					"com.rabbitmq:amqp-client:5.29.0",
					'com.google.j2objc:j2objc-annotations:3.0.0'
		}
	}
}

dependencies {
	//Core decides what logging implementation to use. So, excluding dependencies of th2-common
	api platform("com.exactpro.th2:bom:${bomVersion}") {
		exclude (group: 'org.apache.logging.log4j')
		exclude (group: 'org.slf4j')
	}
	api ('com.exactpro.th2:common:5.17.2-dev') {
		exclude (group: 'org.apache.logging.log4j')
		exclude (group: 'org.slf4j')
	}
	api ('com.exactpro.th2:grpc-check1:4.5.2') {
		exclude (group: 'org.apache.logging.log4j')
		exclude (group: 'org.slf4j')
	}
	api ('com.exactpro.th2:common-utils:2.4.0-dev') {
		exclude (group: 'org.apache.logging.log4j')
		exclude (group: 'org.slf4j')
	}
	
	api 'com.google.code.gson:gson:2.13.1'
	
	api 'org.apache.httpcomponents:fluent-hc:4.5.13'
	api 'org.apache.httpcomponents:httpclient:4.5.13'
	api 'org.apache.httpcomponents.core5:httpcore5:5.4.3'
	
	def log4jVersion = '2.22.1'
	testImplementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"
	testImplementation "org.apache.logging.log4j:log4j-slf4j2-impl:${log4jVersion}"
	testImplementation "org.apache.logging.log4j:log4j-jcl:${log4jVersion}"
}

publishing {
	publications {
		th2(MavenPublication) {
			groupId = "${group}"
			artifactId = 'clearth-th2'
			version = "${version}"
			
			from components.java
		}
	}
}

artifactoryPublish {
	publications(publishing.publications.th2)
}

ext {
	moduleName = 'th2'
	moduleImpl = 'com.exactprosystems.clearth:clearth-th2'
	if (!project.hasProperty('clearthDir'))
		clearthDir = undef
	installationDir = "${projectDir}/installation"
	clearthCfgDir = "${clearthDir}/cfg/"
}

task installModule {
	doLast {
		def actions = file("${projectDir}/installation/actions.cfg").text
		
		def type = new Tuple4("th2 loader",
				"com.exactprosystems.clearth.connectivity.th2.Th2LoaderConnection",
				"connections/th2loader",
				[])
		installModule(clearthDir, moduleName, moduleImpl,
				[
					{ putDataHandlersFactory(clearthDir, 'com.exactprosystems.clearth.data.th2.Th2DataHandlersFactory') },
					{ putFile("th2/box.json", installationDir, clearthCfgDir) },
					{ putFile("th2/storage.json", installationDir, clearthCfgDir) },
					{ putFile("th2/mq.json", installationDir, clearthCfgDir) },
					{ putFile("th2/rabbitMQ.json", installationDir, clearthCfgDir) },
					{ addConnectionTypeToCfg(type, clearthDir) },
					{ putActions(clearthDir, actions) }
				]
		)
		println("Please complete setup by updating files in ${clearthCfgDir}/th2/")
	}
}

def putDataHandlersFactory(clearthDir, factoryToAdd) {
	File cfg = getClearThCfg(clearthDir)
	Node rootNode = getClearThRootNode(cfg)
	Node updatedRootNode = putDataHandlersFactory(rootNode, factoryToAdd)
	updateClearThCfg(cfg, updatedRootNode)
	
	println("- DataHandlersFactory '${factoryToAdd}' put to clearth.cfg")
}

static Node putDataHandlersFactory(Node rootNode, factoryToAdd) {
	String dataNodeName = 'data'
	String factoryNodeName = 'dataHandlersFactory'
	Node dataNode = rootNode.get(dataNodeName)?.getAt(0)
	if (!dataNode) {
		dataNode = rootNode.appendNode(dataNodeName)
	}
	else {
		Node factoryNode = dataNode.get(factoryNodeName)?.getAt(0)
		if (factoryNode) {
			dataNode.remove(factoryNode)
		}
	}
	dataNode.appendNode(factoryNodeName, factoryToAdd)
	return rootNode
}