dependencies {
	api 'org.apache.httpcomponents.client5:httpclient5-fluent:5.6.4'
	api 'org.apache.httpcomponents.client5:httpclient5:5.6.4'
	api 'org.apache.httpcomponents.client5:httpclient5-cache:5.6.4'
	api 'org.apache.httpcomponents.client5:httpclient5-win:5.2.3'
	api 'org.apache.httpcomponents.core5:httpcore5:5.4.3'
	api 'io.netty:netty-all:4.2.18.Final'
}

publishing {
	publications {
		rh(MavenPublication) {
			groupId = "${group}"
			artifactId = 'clearth-rh'
			version = "${version}"
			
			from components.java
		}
	}
}

artifactoryPublish {
	publications(publishing.publications.rh)
}

ext {
	moduleName = 'RemoteHand'
	moduleImpl = 'com.exactprosystems.clearth:clearth-rh'
	if (!project.hasProperty('clearthDir'))
		clearthDir = undef
}

task installModule {
	doLast {
		def installationDir = "${projectDir}/installation"
		def actions = file("${installationDir}/actions.cfg").text

		def type = new Tuple4("RemoteHand",
					"com.exactprosystems.clearth.connectivity.remotehand.RhConnection",
					"connections/remotehand",
					[])

		installModule(clearthDir, moduleName, moduleImpl,
				[
						{ addConnectionTypeToCfg(type, clearthDir) },
						{ putActions(clearthDir, actions) }
				]
		)
	}
}